name: "Build FoodGrab"
on:
  pull_request:
    branches:
      - '2024/Q1/ci_cd/validate/develop'

jobs:
  merge_job:
    runs-on: macos-latest
    steps:
      - name: Merge Pull Request
        if: github.event.pull_request.merged == true
        run: |
          git config user.name "j8bok"
          git config user.email "jayvee.d.ercia@gmail.com"
          git fetch origin 2024/Q1/ci_cd/validate/develop
          git checkout 2024/Q1/ci_cd/validate/develop
          git merge --no-ff 2024/Q1/ci_cd/issues/FG-010 -m "Merge 2024/Q1/ci_cd/issues/FG-010 into 2024/Q1/ci_cd/validate/develop"

          # Push the merged changes back to the repository
          git push origin 2024/Q1/ci_cd/validate/develop

  
