name: "Build FoodGrab"
on:
  pull_request:
    branches:
      - '2024/Q1/ci_cd/validate/develop'

merge_job:
    runs-on: macos-latest
    steps:
      - name: Merge Pull Request
        if: github.event.pull_request.merged == true
        run: |
          git config user.name "j8bok"
          git config user.email "jayvee.d.ercia@gmail.com"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.pull_request.number }}"

          # Push the merged changes back to the repository
          git push origin ${{ github.event.pull_request.base.ref }}

  
