name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Add automerge label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['automerge']
            });
