# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
 desc "export ipa"
 lane :export_ipa do
    gym(
      project: "FoodGrab.xcodeproj",
      scheme: "FoodGrab",
      clean: true,
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        provisioningProfiles: {
          "com.FoodGrab" => "FoodGrab-Distribution"
        },
        "method": "enterprise",
        "signingStyle": "manual"
      },
      output_name: "FoodGrab.ipa",
      output_directory: "/Users/opsolutions/Desktop/myGithubRepositories/iOS/FoodGrab/ipa"
      )
  end
end

